config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'home#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :spaceships
  resources :jobs
  resources :spaceship_jobs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :spaceships
	has_many :spaceship_jobs
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
	has_many :jobs
	has_many :spaceship_jobs
	belongs_to :user

	validates :name, uniqueness: true
	mount_uploader :avatar, AvatarUploader

end

app/models/spaceship_job.rb
class SpaceshipJob < ApplicationRecord
	belongs_to :spaceship
	belongs_to :job
	
	validates :job_id, :uniqueness => {:scope => :spaceship}

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :jobs
	has_many :spaceships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:fleet])
   update_attrs = [:email, :name, :fleet, :password, :password_confirmation, :current_password]
  devise_parameter_sanitizer.permit :account_update, keys: update_attrs
 end

 def after_sign_in_path_for(resource)
   user_path(resource)
 end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @Jobs = Job.all
  end

  def edit
    @Jobs = Job.find(params[:id])
    puts @Jobs.inspect
  end

  def update

    @Jobs = Job.find(params[:id])
    @Jobs.update_attributes(description: params[:job][:description], origin: params[:job][:origin], destination: params[:job][:destination], cost: params[:job][:cost], containers_needed: params[:job][:containers_needed])
    @Jobs.save
    redirect_to '/jobs'
  end

  def show
    @Jobs = Job.find(params[:id])
  end

  def destroy
    @Jobs = Job.find(params[:id])
    @SpaceshipJobs = SpaceshipJob.where({job_id: @Jobs.id})
    @SpaceshipJobs.destroy_all
    @Jobs.destroy
    redirect_to '/jobs'
  end

  def new
    @Jobs = Job.new
  end

  def create
    @Jobs = Job.create(description: params[:job][:description], origin: params[:job][:origin], destination: params[:job][:destination], cost: params[:job][:cost], containers_needed: params[:job][:containers_needed])
    @Jobs.save
    redirect_to '/jobs'
  end

end

app/controllers/spaceship_jobs_controller.rb
class SpaceshipJobsController < ApplicationController
  def index
    @Spaceships = Spaceship.all
    @Jobs= Job.all
  end

  def edit

  end

  def update
    @User = current_user.id
    @current_user = current_user

  end

  def show

  end

  def destroy

  end

  def new


  end

  def create

    @spaceshipjob = SpaceshipJob.create(spaceship_id: params[:spaceshipjob][:spaceship_id], job_id: params[:spaceshipjob][:job_id])
    @spaceshipjob.save

#fix multuple being assigned to multiple
    if @spaceshipjob.save
					redirect_to current_user
				else
					flash[:notice]="Ship has already been added to this job."
					render :new
				end

  end

end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  def index
    @Spaceships = Spaceship.all
  end

  def edit
    @Spaceships = Spaceship.find(params[:id])
    puts @Spaceships.inspect
  end

  def update
    @User = current_user.id
    @current_user = current_user
    @Spaceships = Spaceship.find(params[:id])
    @Spaceships.update_attributes(name: params[:spaceship][:name], capacity: params[:spaceship][:capacity], location: params[:spaceship][:location],avatar: params[:spaceship][:avatar], user_id: @User )
    @Spaceships.save
    redirect_to @current_user
  end

  def show
    @Spaceships = Spaceship.find(params[:id])
    user_id = Spaceship.select(:user_id).find(params[:id])
    @User = @Spaceships.user

    @Sships = Spaceship.all
    @Jobs = Job.all
    @SpaceshipJobs = SpaceshipJob.all

  end

  def destroy
    @current_user = current_user
    @Spaceships = Spaceship.find(params[:id])
    @SpaceshipJobs = SpaceshipJob.where({spaceship_id: @Spaceships.id})
    @SoaceshipJobs.destroy_all
    @Spaceships.destroy
    redirect_to @current_user
  end

  def new
    @Spaceships = Spaceship.new
  end

  def create
    @User = current_user.id
    @current_user = current_user
    @Spaceships = Spaceship.create(name: params[:spaceship][:name], capacity: params[:spaceship][:capacity], location: params[:spaceship][:location], avatar: params[:spaceship][:avatar], user_id: @User)
    if @Spaceships.save
          respond_to do |format|
            format.html { redirect_to spaceship_path(@Spaceships) }
            format.js
          end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@Users = User.all
	end

	def show
		@User = User.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/spaceship_jobs_helper.rb
module SpaceshipJobsHelper
end

app/helpers/spaceships_helper.rb
module SpaceshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>

app/views/jobs/edit.html.erb
<h1>Edit an Existing Job</h1>

<%= form_for @Jobs do |f| %>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :origin %><br>
    <%= f.text_area :origin %>
  </p>

    <p>
    <%= f.label :destination %><br>
    <%= f.text_area :destination %>
  </p>

      <p>
    <%= f.label :cost %><br>
    <%= f.text_area :cost %>
  </p>

      <p>
    <%= f.label :containers_needed %><br>
    <%= f.text_area :containers_needed %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/jobs/index.html.erb
<h1 style = "text-align: center; padding-bottom: 50px;">Here is a list of Jobs</h1>
<div class = 'container'>
  <div class = 'row'>
    <div class= 'col joblists'>
      <% @Jobs.each do |t| %>
      <h4><%= t.description %></h4>
      <a class = 'links' href = '/jobs/<%= t.id %>/edit'>Edit</a>
      <%= link_to 'Delete',  t,  method: :delete, :class => 'links'%>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<h1 style = 'text-align: center;'>Create a New Job</h1>

<div class  = 'container createjob'>
  <%= form_for :job, url: jobs_path do |f| %>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description, :minlength => 50%>
  </p>

  <p>
    <%= f.label :origin %><br>
    <%= f.text_area :origin %>
  </p>

  <p>
    <%= f.label :destination %><br>
    <%= f.text_area :destination %>
  </p>

  <p>
    <%= f.label :cost %><br>
    <%= f.text_area :cost %>
  </p>

  <p>
    <%= f.label :containers_needed %><br>
    <%= f.text_area :containers_needed %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanetExpress</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>




  </head>

  <body>

	  <nav class="navbar navbar-default navbar-inverse" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <img class= "rocket" src="<%= asset_path( 'rocket.png' ) %>" />

		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li class="active"><a href="/spaceships">Spaceships</a></li>
		        <li><a href="/jobs">Jobs</a></li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profile <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="/users/sign_in">User</a></li>
		            <li><a href="/spaceships/new">Create a Spaceship</a></li>
		            <li><a href="/spaceship_jobs/new">Add a Job</a></li>
		            <li class="divider"></li>
		            <li><a href="/jobs/new">Post a New Job</a></li>
		          </ul>
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

    <%= yield %>
    <footer class="footer">
  <div class="container">
<ul class="social-icon animate pull-right">
              <li><a href="#" title="facebook" target="_blank"><i class="fa fa-facebook"></i></a></li> <!-- change the link to social page and edit title-->
              <li><a href="#" title="twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#" title="google plus" target="_blank"><i class="fa fa-google-plus"></i></a></li>
            </ul>
            </div>
</footer>
  </body>
</html>

app/views/spaceship_jobs/new.html.erb
<h1 style = 'text-align:center;'>Add a Job to your Spaceship Here!</h1>
<div class = 'container spaceshipjob'>
  <%=form_for SpaceshipJob.new do |f| %>
  <% @spaceship = Spaceship.where(user_id: current_user) %>
    <p><%= f.label :'Choose a Spaceship' %></p>
    <p><%= collection_select(:spaceshipjob, :spaceship_id, @spaceship, :id, :name, :prompt =>true)%></p>

    <p><%= f.label :'Then Pick a Job' %></p>
    <p><%= collection_select(:spaceshipjob, :job_id, Job.all, :id, :description, :prompt =>true)%> </p>
    <p><%=f.submit%></p>
  <%end%>
  <%= flash[:notice] %>
</div>

app/views/spaceships/create.js.erb
$("#listofships").text("Your ship has been created! <%= @Spaceships.name %> <%= @Spaceships.location %>");

app/views/spaceships/edit.html.erb
<h1>Edit Spaceship</h1>

<%= form_for @Spaceships do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :capacity %><br>
    <%= f.text_field :capacity %>
  </p>

    <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :image%><br>
    <%= f.file_field :avatar%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/spaceships/index.html.erb
<h1 style = 'text-align:center;'>These are all the Spaceships in the Universe!</h1>

<div class = 'container allspaceships'>
  <% @Spaceships.each do |t| %>
  <h3>
    <a class = 'links' href = '/spaceships/<%= t.id %>show'><%= t.name %></a>
  </h3>
  <%end%>
</div>

app/views/spaceships/new.html.erb
<div class 'container'>
  <h1 id = 'newspaceship'>New Spaceship</h1>
  <%= form_for Spaceship.new, remote: true do |f| %>
    <p class = 'newspaceshipform'>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p class = 'newspaceshipform'>
      <%= f.label :capacity %><br>
      <%= f.text_field :capacity %>
    </p>

      <p class = 'newspaceshipform'>
      <%= f.label :location %><br>
      <%= f.text_field :location %>
    </p>
      <p class = 'newspaceshipform'>
        <%= f.label :image%>
  			<%= f.file_field (:avatar), :id=>'newspaceshipimage'%>
      </p>
      <br>
    <p class = 'newspaceshipform'>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/spaceships/show.html.erb
<h1><%= @Spaceships.name %></h1>

<img src="<%= @Spaceships.avatar%>">


<h3>Jobs under this ship</h3>

<% if user_signed_in? %>
  <% @Sships.where({user_id: current_user.id}).each do |s| %>
    <%@SpaceshipJobs.where({spaceship_id: s.id}).each do |j| %>
    <p><%=@Jobs.find(j.job_id).description%></p>
    <%end%>
  <%end%>
<%end%>

app/views/users/index.html.erb
<h1>Hello</h1>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class 'container'>
    <h1 id = 'usrname'>Hello <%=@User.name%></h1>
      <li class = "logout">
        <%= link_to "Change your password |", edit_user_registration_path, :class => 'links'%>
        <%= link_to('Logout |', destroy_user_session_path, method: :delete, :class => 'links') %>
        <%= link_to('Spaceships', spaceships_path, method: :get, :class => 'links') %>
      </li>


  <div class 'row'>
    <h1 id = 'fleet'><%=@User.fleet%></h1>
    <div class = 'col-sm-4' id= 'fleetlist'>
      <% @User.spaceships.each do |t| %>
        <a class = 'links' href = '/spaceships/<%=t.id%>show'><h3><%= t.name %></h3></a>
        <img src="<%=t.avatar.thumb%>" class = 'links avatarr'>
        <ul >
          <li class = 'userlist' ><a class = 'links' href = '/spaceships/<%= t.id %>/edit'>Edit</a></li>
          <li class = 'userlist' ><%= link_to 'Delete',  t,  method: :delete, :class => 'links' %></li>
        </ul>
      <% end %>
    </div>
    </div>
    <div class= 'col-sm-4'>

    </div>

    <div class = 'col-sm-4' id = "createadd">
    <h2 class = 'links'><%= link_to('Create Spaceship', new_spaceship_path, method: :get, :class => 'links' ) %></h2>
    <h4>
      You can create a new spaceship to add to your fleet!
    </h4>
    <h2 class = 'links'><%= link_to('Add a Job', new_spaceship_job_path, method: :get, :class => 'links') %></h2>
    <h4>
      You can also add a job to any spaceship under your Profile!
    </h4>
    </div>
  </div>